[build]
  publish = "."

# =========================
# URLs limpas → arquivos HTML (200)
# =========================
[[redirects]] # páginas institucionais
  from = "/sobrenos"
  to   = "/paginas/sobrenos.html"
  status = 200
[[redirects]]
  from = "/servicos"
  to   = "/paginas/servicos.html"
  status = 200
[[redirects]]
  from = "/obras"
  to   = "/paginas/obras.html"
  status = 200
[[redirects]]
  from = "/empreendimentos"
  to   = "/paginas/empreendimentos.html"
  status = 200
[[redirects]]
  from = "/sustentabilidade"
  to   = "/paginas/sustentabilidade.html"
  status = 200
[[redirects]]
  from = "/noticias"
  to   = "/paginas/noticias.html"
  status = 200
[[redirects]]
  from = "/simulacao"
  to   = "/paginas/simulacao.html"
  status = 200
[[redirects]]
  from = "/trabalheconosco"
  to   = "/paginas/trabalheconosco.html"
  status = 200
[[redirects]]
  from = "/contato"
  to   = "/paginas/contato.html"
  status = 200

# =========================
# Headers globais de segurança
# =========================
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(self), microphone=(), camera=()"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; script-src 'self'; connect-src 'self' https://api.rss2json.com; img-src 'self' data: https:; style-src 'self' 'unsafe-inline'; font-src 'self' data:; frame-ancestors 'none'; form-action 'self' https://wa.me; base-uri 'self'; object-src 'none'; worker-src 'self'; manifest-src 'self'; upgrade-insecure-requests"

# =========================
# Cache leve para páginas (opcional em dev)
# =========================
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
